version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 060923
      MYSQL_DATABASE: minedb
      MYSQL_USER: bxit
      MYSQL_PASSWORD: aa
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql