services:
  postgres:
    container_name: news-app
    image: postgres
    environment:
      POSTGRES_USER: bxit
      POSTGRES_PASSWORD: aa
      PGDATA: /data/postgresql
    volumes:
      - bxit-db:/data/postgresql
    ports:
      - "5433:5432"
    restart: unless-stopped
volumes:
  bxit-db: